// <auto-generated />
using InsurancePortalWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsurancePortalWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241223182402_RemovedPrice2312")]
    partial class RemovedPrice2312
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsurancePortalWeb.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Comprehensive health insurance for individuals.",
                            ImageUrl = "https://example.com/images/health-insurance-a.jpg",
                            Name = "Health Insurance Plan A",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Full coverage car insurance with roadside assistance.",
                            ImageUrl = "https://example.com/images/car-insurance-b.jpg",
                            Name = "Car Insurance Plan B",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Protection for your home and belongings.",
                            ImageUrl = "https://example.com/images/home-insurance-c.jpg",
                            Name = "Home Insurance Plan C",
                            Price = 399.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
