// <auto-generated />
using System;
using InsurancePortalWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsurancePortalWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241222201014_InitialMigration3")]
    partial class InitialMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsurancePortalWeb.Models.Insurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7997d4d-4d56-4c6a-a684-41c6c2329ef1"),
                            Description = "Comprehensive health insurance for individuals.",
                            ImageUrl = "https://example.com/images/health-insurance-a.jpg",
                            Name = "Health Insurance Plan A",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = new Guid("b849b20c-2d79-48c2-82a7-631d21357e67"),
                            Description = "Full coverage car insurance with roadside assistance.",
                            ImageUrl = "https://example.com/images/car-insurance-b.jpg",
                            Name = "Car Insurance Plan B",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = new Guid("6fa1b91f-f84d-4c0c-8815-d6c62251cc3b"),
                            Description = "Protection for your home and belongings.",
                            ImageUrl = "https://example.com/images/home-insurance-c.jpg",
                            Name = "Home Insurance Plan C",
                            Price = 399.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
